### ISSUE TITLE
为什么链接里设置了，首页没显示呢？

### ISSUE THREAD

**Issue by BG7ZAG** [D-xuanmo/Nuxtjs-Wordpress#10]
刚更新的最新版，后台链接里之前有设置了，但首页没显示

**Comment by D-xuanmo** [comment]
@hlbj105 在链接管理增加一个分类，命名为首页，如果需要在首页展示的就勾选一下这个分类

**Comment by BG7ZAG** [comment]
直接默认显示全部就可以吗？每个链接编辑里面有一个设为私密链接的选项，设为私密链接就不显示了

**Comment by BG7ZAG** [comment]
还有就是列表的多行超出隐藏的那个height应该不用设置，
global.scss
```
.summary {
    display: -webkit-box;
    overflow: hidden;
    // height: 80px;
    -webkit-box-orient: vertical;
    word-break: break-all;
    text-overflow: ellipsis;
    -webkit-line-clamp: 3;
    line-height: 1.8;
  }
```

**Comment by D-xuanmo** [comment]
@hlbj105 
问题1：主要是考虑链接分类方便管理，目前考虑到可能内页的友情链接可能也会放在这里管理，所以就加上了分类
问题2：之所以列表多行隐藏加上一个高度主要是为了考虑到firefox非webkit内核浏览器的兼容

**Comment by BG7ZAG** [comment]
这样啊，不过这个高度是不是该小一点？都漏出下面的文字了，一直没做过Firefox的兼容。。。

**Comment by D-xuanmo** [comment]
@hlbj105 已修复，改为scss自动计算高度
