### ISSUE TITLE
Error:  Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by willin** [D-xuanmo/Nuxtjs-Wordpress#2]
https://github.com/xuanmos/xm-nuxtjs-wordpress/blob/master/pages/details/_id.vue#L237

what does these strange codes mean?

**Comment by D-xuanmo** [comment]
> https://github.com/xuanmos/xm-nuxtjs-wordpress/blob/master/pages/details/_id.vue#L237
> 
> what does these strange codes mean?

@willin Here replace the logo address used to generate the poster with replace. The error may be that the value of this field is null.

**Comment by willin** [comment]
how to set one？

**Comment by D-xuanmo** [comment]
@willin Upload in my profile.

**Comment by willin** [comment]
but i already have one using gravatar

**Comment by D-xuanmo** [comment]
@willin  This is a bug. I didn't take this into account when I was doing it. This gravatar is mainly localized. I need to change it.

**Comment by willin** [comment]
thx

**Comment by D-xuanmo** [comment]
It has been modified.
